--<ScriptOptions statementTerminator=";"/>

CREATE TABLE DEPARTMENT (
		DEPTNO CHAR(3) NOT NULL, 
		DEPTNAME VARCHAR(36) NOT NULL, 
		MGRNO CHAR(6), 
		ADMRDEPT CHAR(3) NOT NULL, 
		LOCATION CHAR(16)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE DEPARTMENT ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY
	(DEPTNO);

