--<ScriptOptions statementTerminator=";"/>

CREATE TABLE EMPLOYEE (
		EMPNO CHAR(6) NOT NULL, 
		FIRSTNME VARCHAR(12) NOT NULL, 
		MIDINIT CHAR(1), 
		LASTNAME VARCHAR(15) NOT NULL, 
		WORKDEPT CHAR(3), 
		PHONENO CHAR(4), 
		HIREDATE DATE, 
		JOB CHAR(8), 
		EDLEVEL SMALLINT NOT NULL, 
		SEX CHAR(1), 
		BIRTHDATE DATE, 
		SALARY DECIMAL(9 , 2), 
		BONUS DECIMAL(9 , 2), 
		COMM DECIMAL(9 , 2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE EMPLOYEE ADD CONSTRAINT PK_EMPLOYEE PRIMARY KEY
	(EMPNO);

