--<ScriptOptions statementTerminator=";"/>

CREATE TABLE EMPPROJACT (
		EMPNO CHAR(6) NOT NULL, 
		PROJNO CHAR(6) NOT NULL, 
		ACTNO SMALLINT NOT NULL, 
		EMPTIME DECIMAL(5 , 2), 
		EMSTDATE DATE, 
		EMENDATE DATE
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

