--<ScriptOptions statementTerminator=";"/>

CREATE TABLE PROJECT (
		PROJNO CHAR(6) NOT NULL, 
		PROJNAME VARCHAR(24) NOT NULL DEFAULT '', 
		DEPTNO CHAR(3) NOT NULL, 
		RESPEMP CHAR(6) NOT NULL, 
		PRSTAFF DECIMAL(5 , 2), 
		PRSTDATE DATE, 
		PRENDATE DATE, 
		MAJPROJ CHAR(6)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE PROJECT ADD CONSTRAINT PK_PROJECT PRIMARY KEY
	(PROJNO);

