name: gtk_flutter
description: Get to know Firebase with Flutter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.12.0-259.16.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0

flutter:
  uses-material-design: true
  assets:
   - assets/codelab.png
