-- 1 - 4 is SELECT * FOR each tables
-- 5.) Find female employees. Show their name, date of birth, phone, and salary
SELECT FIRSTNME, LASTNAME, BIRTHDATE, PHONENO, SALARY
FROM EMPLOYEE
WHERE SEX = 'F';

-- 6.) Find name, job, and salary of employee who earns more than $80000
SELECT FIRSTNME, LASTNAME, JOB, SALARY
FROM EMPLOYEE
WHERE SALARY > 80000;

-- 6.2) Is there any woman in the answer
SELECT FIRSTNME, LASTNAME, JOB, SALARY, SEX
FROM EMPLOYEE
WHERE SALARY > 80000 AND SEX = 'F';

-- 6.3) Order the result of 6.2 by salary. Show the highest salary first
SELECT FIRSTNME, LASTNAME, JOB, SALARY
FROM EMPLOYEE
WHERE SALARY > 80000
ORDER BY SALARY DESC;

-- 7.) Show name, job, salary, and hiredate of the top three most salary employees
SELECT FIRSTNME, LASTNAME, JOB, SALARY, HIREDATE
FROM EMPLOYEE
ORDER BY SALARY DESC
FETCH FIRST 3 ROWS ONLY; -- SAME AS LIMIT 3

-- 8.) Show name and their total income
SELECT FIRSTNME, LASTNAME, SALARY, BONUS, COMM, SALARY + BONUS + COMM AS TOTAL
FROM EMPLOYEE;

-- 9.) SHow only person who earn the total income more than 100,000. Order by lastname
SELECT FIRSTNME, LASTNAME, SALARY + BONUS + COMM AS TOTAL
FROM EMPLOYEE
WHERE SALARY + BONUS + COMM > 100000
ORDER BY LASTNAME;

-- 10.) Who would earn more than $75,000 if the company raise the salary by 5%
SELECT FIRSTNME, LASTNAME, SALARY, SALARY*1.05 AS RAISEDSALARY
FROM EMPLOYEE
WHERE SALARY * 1.05 > 75000

-- 11.) Who cross the 75,000 if the company raise the salary by 5%
SELECT FIRSTNME, LASTNAME, SALARY, SALARY*1.05 AS RAISEDSALARY
FROM EMPLOYEE
WHERE SALARY < 75000 AND SALARY * 1.05 > 75000;

-- 12.) Who are older than 45 years?
SELECT FIRSTNME, LASTNAME, BIRTHDATE, CURRENT_DATE - BIRTHDATE AS YYMMDD, YEAR(CURRENT_DATE - BIRTHDATE) AS AGE
FROM EMPLOYEE
WHERE YEAR(CURRENT_DATE - BIRTHDATE) > 45;

-- 13.) Show name, job title, and their department
SELECT FIRSTNME, LASTNAME, JOB, DEPTNAME
FROM EMPLOYEE, DEPARTMENT
WHERE WORKDEPT = DEPTNO;

-- 14.) Who are the missing person of question 14?
SELECT FIRSTNME, WORKDEPT
FROM EMPLOYEE
WHERE WORKDEPT NOT IN (SELECT DEPTNO FROM DEPARTMENT);

-- 15.) Show all detail of projects
SELECT *
FROM PROJECT;

-- 16.) Opal wants to know who works on payroll project
SELECT PROJNAME, EMPLOYEE.EMPNO, FIRSTNME, LASTNAME
FROM EMPPROJACT, PROJECT, EMPLOYEE
WHERE PROJECT.PROJNO = EMPPROJACT.PROJNO AND
      EMPPROJACT.EMPNO = EMPLOYEE.EMPNO AND
      PROJNAME = 'PAYROLL PROGRAMMING';

-- 17.) Opal complains "DO NOT SHOW ME THE REPEATING RESULT!"
SELECT DISTINCT PROJNAME, EMPLOYEE.EMPNO, FIRSTNME, LASTNAME
FROM EMPPROJACT, PROJECT, EMPLOYEE
WHERE PROJECT.PROJNO = EMPPROJACT.PROJNO AND
      EMPPROJACT.EMPNO = EMPLOYEE.EMPNO AND
      PROJNAME = 'PAYROLL PROGRAMMING';

-- 18.) Opal said I want any payroll project, not only payroll programming.
SELECT DISTINCT PROJNAME, EMPLOYEE.EMPNO, FIRSTNME, LASTNAME
FROM EMPPROJACT, PROJECT, EMPLOYEE
WHERE PROJECT.PROJNO = EMPPROJACT.PROJNO AND
      EMPPROJACT.EMPNO = EMPLOYEE.EMPNO AND
      PROJNAME LIKE '%PAYROLL%';

-- 19.) Who works on the project that start before 2020-01-01. Show their name and their department.
SELECT FIRSTNME, LASTNAME, DEPTNAME
FROM DEPARTMENT, EMPLOYEE, EMPPROJACT, PROJECT
WHERE DEPARTMENT.DEPTNO = EMPLOYEE.WORKDEPT AND
      EMPLOYEE.EMPNO = EMPPROJACT.EMPNO AND
      EMPPROJACT.PROJNO = PROJECT.PROJNO AND
      PROJECT.PRSTDATE < '2010-01-01';

-- 20.) Who are older than the president
-- SELECT FIRSTNME, LASTNAME, YEAR(CURRENT_DATE - BIRTHDATE) AS AGE
-- FROM EMPLOYEE
-- WHERE YEAR(CURRENT_DATE - BIRTHDATE) > (
--     SELECT YEAR(CURRENT_DATE - BIRTHDATE)
--     FROM EMPLOYEE
--     WHERE JOB = 'PRES'
-- )
SELECT E.FIRSTNME, E.LASTNAME, e.BIRTHDATE, p.BIRTHDATE
FROM EMPLOYEE as P, EMPLOYEE as E
WHERE P.JOB = 'PRES' AND E.BIRTHDATE < P.BIRTHDATE;

